name: Exploring Variables and Secrets

on:
  workflow_dispatch: 
  # schedule:
  #   - cron: '*/1 * * * *'
  push:

env:
    CONTAINER_REGISTRY: docker.io
    IMAGE_NAME: github-actions-nginx    

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Build
      run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

    - name: Docker Login
      run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Publish
      run: echo docker push $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

  deploy:
    if: github.ref == 'refs/heads/master'
    needs: docker
    # Cocurrency is enabled when you dont want two jobs to run together
    # Allows only one job or one workflow to run at a time
    concurrency: 
      group: production-deployment # Unique name
      # If it is false it will wait for old job/workflow to be completed
      # if it is true new job will be terminated since old job is still executing
      cancel-in-progress: false 

    runs-on: ubuntu-latest
    steps:
    - name: Docker Run
      # Timeout minutes says to terminate job if it exceeds 1min
      timeout-minutes: 1
      run: |
        echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest
        sleep 120s